title: Nate Givens
description: >
  Welcome to my website!
remote_theme: jekyll/minima

# Minima theme customization
minima:
  skin: dark

# Navigation
header_pages:
  - index.md
  - about.md
  - stories.md
  - blog.md